language: csharp
mono: none
dotnet: 3.1
os:
  - linux
sudo: required
dist: xenial
env:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true DOTNET_CLI_TELEMETRY_OPTOUT=true
before_script:
  - chmod a+x ./build.sh
script:
  - ./build.sh --target=Travis --verbosity=Diagnostic
